$color = rgba(0, 0, 0, 1)
$inner_color = rgba(0, 0, 0, 0.66)
$outer_color = rgba(234, 136, 146, 1)
$font_color = rgba(244, 238, 227, 1)
$placeholder_color = rgba(244, 238, 227, 0.7)
$check_color = rgba(255, 199, 102, 1)
